apiVersion: v2
appVersion: "1.0"
description: A Helm chart for opal-print-service App
name: opal-print-service
home: https://github.com/hmcts/opal-print-service
version: 0.0.18
maintainers:
  - name: HMCTS Opal team
dependencies:
  - name: java
    version: 5.2.0
    repository: 'https://hmctspublic.azurecr.io/helm/v1/repo/'
